/**
 * Resultado Primarias Alcaldes Junio 2016
 * Datos agregados por región y partido desde votación por comuna
 */
export const alcaldesPrimaria201606 = {
    id: "alcaldes-primaria-2016-06",
    name: "Primarias Alcaldes Junio 2016",
    // Mapeo de cada partido a su pacto correspondiente
    pactoMapping: {
        "INDEPENDIENTES LISTA A": "CHILE VAMOS",
        "INDEPENDIENTES LISTA B": "NUEVA MAYORIA",
        "MAS REGION": "NUEVA MAYORIA",
        "PARTIDO COMUNISTA DE CHILE": "NUEVA MAYORIA",
        "PARTIDO DEMOCRATA CRISTIANO": "NUEVA MAYORIA",
        "PARTIDO EVOLUCION POLITICA": "CHILE VAMOS",
        "PARTIDO IZQUIERDA CIUDADANA DE CHILE": "NUEVA MAYORIA",
        "PARTIDO POR LA DEMOCRACIA": "NUEVA MAYORIA",
        "PARTIDO RADICAL SOCIALDEMOCRATA": "NUEVA MAYORIA",
        "PARTIDO REGIONALISTA INDEPENDIENTE": "CHILE VAMOS",
        "PARTIDO SOCIALISTA DE CHILE": "NUEVA MAYORIA",
        "RENOVACION NACIONAL": "CHILE VAMOS",
        "UNION DEMOCRATA INDEPENDIENTE": "CHILE VAMOS",
        "VOTOS EN BLANCO": "VOTOS EN BLANCO",
        "VOTOS NULOS": "VOTOS NULOS"
    },
    // Votos desglosados por región
    votesByRegion: {
        "1": { "INDEPENDIENTES LISTA A": 0, "INDEPENDIENTES LISTA B": 353, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 1153, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 900, "PARTIDO RADICAL SOCIALDEMOCRATA": 0, "PARTIDO REGIONALISTA INDEPENDIENTE": 136, "PARTIDO SOCIALISTA DE CHILE": 225, "RENOVACION NACIONAL": 2115, "UNION DEMOCRATA INDEPENDIENTE": 2707, "VOTOS EN BLANCO": 167, "VOTOS NULOS": 287 },
        "2": { "INDEPENDIENTES LISTA A": 688, "INDEPENDIENTES LISTA B": 0, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 802, "PARTIDO DEMOCRATA CRISTIANO": 1709, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 792, "PARTIDO RADICAL SOCIALDEMOCRATA": 2234, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 2794, "RENOVACION NACIONAL": 436, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 289, "VOTOS NULOS": 677 },
        "3": { "INDEPENDIENTES LISTA A": 238, "INDEPENDIENTES LISTA B": 3713, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 390, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 3233, "PARTIDO RADICAL SOCIALDEMOCRATA": 234, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 3388, "RENOVACION NACIONAL": 368, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 85, "VOTOS NULOS": 208 },
        "4": { "INDEPENDIENTES LISTA A": 4165, "INDEPENDIENTES LISTA B": 6966, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 1935, "PARTIDO EVOLUCION POLITICA": 935, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 2309, "PARTIDO RADICAL SOCIALDEMOCRATA": 6005, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 0, "RENOVACION NACIONAL": 693, "UNION DEMOCRATA INDEPENDIENTE": 1949, "VOTOS EN BLANCO": 252, "VOTOS NULOS": 502 },
        "5": { "INDEPENDIENTES LISTA A": 1845, "INDEPENDIENTES LISTA B": 10494, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 9574, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL SOCIALDEMOCRATA": 1304, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 6135, "RENOVACION NACIONAL": 1815, "UNION DEMOCRATA INDEPENDIENTE": 1723, "VOTOS EN BLANCO": 403, "VOTOS NULOS": 1238 },
        "6": { "INDEPENDIENTES LISTA A": 639, "INDEPENDIENTES LISTA B": 0, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 2759, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 205, "PARTIDO RADICAL SOCIALDEMOCRATA": 2500, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 3195, "RENOVACION NACIONAL": 2588, "UNION DEMOCRATA INDEPENDIENTE": 2852, "VOTOS EN BLANCO": 92, "VOTOS NULOS": 371 },
        "7": { "INDEPENDIENTES LISTA A": 0, "INDEPENDIENTES LISTA B": 1994, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 1937, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 1055, "PARTIDO RADICAL SOCIALDEMOCRATA": 1066, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 1629, "RENOVACION NACIONAL": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 78, "VOTOS NULOS": 136 },
        "8": { "INDEPENDIENTES LISTA A": 3928, "INDEPENDIENTES LISTA B": 5070, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 2029, "PARTIDO DEMOCRATA CRISTIANO": 7336, "PARTIDO EVOLUCION POLITICA": 992, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 704, "PARTIDO RADICAL SOCIALDEMOCRATA": 5667, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 4526, "RENOVACION NACIONAL": 7684, "UNION DEMOCRATA INDEPENDIENTE": 8729, "VOTOS EN BLANCO": 621, "VOTOS NULOS": 1352 },
        "9": { "INDEPENDIENTES LISTA A": 2391, "INDEPENDIENTES LISTA B": 3049, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 3132, "PARTIDO EVOLUCION POLITICA": 419, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 784, "PARTIDO RADICAL SOCIALDEMOCRATA": 2025, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 0, "RENOVACION NACIONAL": 4734, "UNION DEMOCRATA INDEPENDIENTE": 6538, "VOTOS EN BLANCO": 252, "VOTOS NULOS": 361 },
        "10": { "INDEPENDIENTES LISTA A": 173, "INDEPENDIENTES LISTA B": 514, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 979, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL SOCIALDEMOCRATA": 695, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 0, "RENOVACION NACIONAL": 176, "UNION DEMOCRATA INDEPENDIENTE": 130, "VOTOS EN BLANCO": 19, "VOTOS NULOS": 17 },
        "13": { "INDEPENDIENTES LISTA A": 1678, "INDEPENDIENTES LISTA B": 4170, "MAS REGION": 195, "PARTIDO COMUNISTA DE CHILE": 4978, "PARTIDO DEMOCRATA CRISTIANO": 8708, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 9536, "PARTIDO RADICAL SOCIALDEMOCRATA": 1578, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 10597, "RENOVACION NACIONAL": 5286, "UNION DEMOCRATA INDEPENDIENTE": 10296, "VOTOS EN BLANCO": 1445, "VOTOS NULOS": 2624 },
        "14": { "INDEPENDIENTES LISTA A": 3255, "INDEPENDIENTES LISTA B": 1378, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 3273, "PARTIDO EVOLUCION POLITICA": 0, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 4635, "PARTIDO RADICAL SOCIALDEMOCRATA": 853, "PARTIDO REGIONALISTA INDEPENDIENTE": 0, "PARTIDO SOCIALISTA DE CHILE": 6557, "RENOVACION NACIONAL": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 213, "VOTOS NULOS": 357 },
        "15": { "INDEPENDIENTES LISTA A": 0, "INDEPENDIENTES LISTA B": 0, "MAS REGION": 0, "PARTIDO COMUNISTA DE CHILE": 1038, "PARTIDO DEMOCRATA CRISTIANO": 1585, "PARTIDO EVOLUCION POLITICA": 781, "PARTIDO IZQUIERDA CIUDADANA DE CHILE": 231, "PARTIDO POR LA DEMOCRACIA": 820, "PARTIDO RADICAL SOCIALDEMOCRATA": 0, "PARTIDO REGIONALISTA INDEPENDIENTE": 298, "PARTIDO SOCIALISTA DE CHILE": 1539, "RENOVACION NACIONAL": 766, "UNION DEMOCRATA INDEPENDIENTE": 2382, "VOTOS EN BLANCO": 209, "VOTOS NULOS": 535 }
    }
};
