/**
 * Resultado Primarias Alcaldes Junio 2024
 * Datos agregados por región y partido desde votación por comuna
 */
export const alcaldesPrimarias202406 = {
    id: "alcaldes-primarias-2024-06",
    name: "Primarias Alcaldes Junio 2024",
    // Mapeo de cada partido a su pacto correspondiente
    pactoMapping: {
        "COMUNES": "CONTIGO CHILE MEJOR",
        "CONVERGENCIA SOCIAL": "CONTIGO CHILE MEJOR",
        "EVOLUCION POLITICA": "CHILE VAMOS",
        "FEDERACION REGIONALISTA VERDE SOCIAL": "CONTIGO CHILE MEJOR",
        "INDEPENDIENTE": "CHILE VAMOS",
        "PARTIDO ACCION HUMANISTA": "CONTIGO CHILE MEJOR",
        "PARTIDO COMUNISTA DE CHILE": "CONTIGO CHILE MEJOR",
        "PARTIDO DEMOCRATA CRISTIANO": "CONTIGO CHILE MEJOR",
        "PARTIDO LIBERAL DE CHILE": "CONTIGO CHILE MEJOR",
        "PARTIDO POR LA DEMOCRACIA": "CONTIGO CHILE MEJOR",
        "PARTIDO RADICAL DE CHILE": "CONTIGO CHILE MEJOR",
        "PARTIDO SOCIAL CRISTIANO": "PARTIDO SOCIAL CRISTIANO E INDEPENDIENTES",
        "PARTIDO SOCIALISTA DE CHILE": "CONTIGO CHILE MEJOR",
        "RENOVACION NACIONAL": "CHILE VAMOS",
        "REVOLUCION DEMOCRATICA": "CONTIGO CHILE MEJOR",
        "UNION DEMOCRATA INDEPENDIENTE": "CHILE VAMOS",
        "VOTOS EN BLANCO": "VOTOS EN BLANCO",
        "VOTOS NULOS": "VOTOS NULOS"
    },
    // Votos desglosados por región
    votesByRegion: {
        "2": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 1574, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 3069, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 2920, "PARTIDO DEMOCRATA CRISTIANO": 1408, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL DE CHILE": 0, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 990, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 243, "VOTOS NULOS": 689 },
        "3": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 279, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 146, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL DE CHILE": 0, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 203, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 13, "VOTOS NULOS": 26 },
        "4": { "COMUNES": 2081, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 8131, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 227, "PARTIDO DEMOCRATA CRISTIANO": 538, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL DE CHILE": 3486, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 606, "RENOVACION NACIONAL": 661, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 274, "VOTOS NULOS": 555 },
        "5": { "COMUNES": 719, "CONVERGENCIA SOCIAL": 3614, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 695, "INDEPENDIENTE": 10942, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 894, "PARTIDO DEMOCRATA CRISTIANO": 2753, "PARTIDO LIBERAL DE CHILE": 407, "PARTIDO POR LA DEMOCRACIA": 2559, "PARTIDO RADICAL DE CHILE": 466, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 1084, "RENOVACION NACIONAL": 2236, "REVOLUCION DEMOCRATICA": 292, "UNION DEMOCRATA INDEPENDIENTE": 779, "VOTOS EN BLANCO": 324, "VOTOS NULOS": 762 },
        "6": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 1668, "INDEPENDIENTE": 7385, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 444, "PARTIDO DEMOCRATA CRISTIANO": 3072, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 1094, "PARTIDO RADICAL DE CHILE": 219, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 4411, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 167, "VOTOS NULOS": 441 },
        "7": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 277, "INDEPENDIENTE": 2003, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 2851, "PARTIDO DEMOCRATA CRISTIANO": 942, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL DE CHILE": 208, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 2073, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 726, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 183, "VOTOS NULOS": 391 },
        "8": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 1507, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 4784, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 1609, "PARTIDO DEMOCRATA CRISTIANO": 2559, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 1848, "PARTIDO RADICAL DE CHILE": 1854, "PARTIDO SOCIAL CRISTIANO": 3892, "PARTIDO SOCIALISTA DE CHILE": 7753, "RENOVACION NACIONAL": 1832, "REVOLUCION DEMOCRATICA": 1153, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 420, "VOTOS NULOS": 1013 },
        "9": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 2802, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 6561, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 197, "PARTIDO DEMOCRATA CRISTIANO": 2856, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 1152, "PARTIDO RADICAL DE CHILE": 907, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 2431, "RENOVACION NACIONAL": 1904, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 397, "VOTOS EN BLANCO": 138, "VOTOS NULOS": 385 },
        "10": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 759, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 395, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 764, "PARTIDO RADICAL DE CHILE": 0, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 0, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 6, "VOTOS NULOS": 14 },
        "11": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 1799, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 245, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL DE CHILE": 0, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 0, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 2805, "VOTOS EN BLANCO": 44, "VOTOS NULOS": 45 },
        "12": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 2508, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 786, "PARTIDO DEMOCRATA CRISTIANO": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL DE CHILE": 0, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 1265, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 79, "VOTOS NULOS": 162 },
        "13": { "COMUNES": 509, "CONVERGENCIA SOCIAL": 2766, "EVOLUCION POLITICA": 478, "FEDERACION REGIONALISTA VERDE SOCIAL": 4630, "INDEPENDIENTE": 51095, "PARTIDO ACCION HUMANISTA": 570, "PARTIDO COMUNISTA DE CHILE": 8089, "PARTIDO DEMOCRATA CRISTIANO": 8332, "PARTIDO LIBERAL DE CHILE": 3232, "PARTIDO POR LA DEMOCRACIA": 2886, "PARTIDO RADICAL DE CHILE": 0, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 10388, "RENOVACION NACIONAL": 13623, "REVOLUCION DEMOCRATICA": 6277, "UNION DEMOCRATA INDEPENDIENTE": 10098, "VOTOS EN BLANCO": 1352, "VOTOS NULOS": 4509 },
        "14": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 126, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 8499, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 123, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 1715, "PARTIDO RADICAL DE CHILE": 434, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 2651, "RENOVACION NACIONAL": 1641, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 1241, "VOTOS EN BLANCO": 107, "VOTOS NULOS": 232 },
        "16": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "FEDERACION REGIONALISTA VERDE SOCIAL": 0, "INDEPENDIENTE": 1346, "PARTIDO ACCION HUMANISTA": 0, "PARTIDO COMUNISTA DE CHILE": 0, "PARTIDO DEMOCRATA CRISTIANO": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO POR LA DEMOCRACIA": 0, "PARTIDO RADICAL DE CHILE": 0, "PARTIDO SOCIAL CRISTIANO": 0, "PARTIDO SOCIALISTA DE CHILE": 0, "RENOVACION NACIONAL": 972, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 2426, "VOTOS EN BLANCO": 20, "VOTOS NULOS": 41 }
    }
};
