export const cCPI202105 = {
  id: "ccpi-2021-05",
  name: "Consejos Constituyentes Pueblos Indígenas Mayo 2021",
  pueblos: [
    "AIMARA",
    "CHANGO",
    "COLLA",
    "DIAGUITA",
    "KAWASHKAR",
    "LICAN ANTAY o ATACAMEÑO",
    "MAPUCHE",
    "OTROS",
    "QUECHUA",
    "RAPA NUI",
    "YAGAN o YÃMANA"
  ],
  votesByRegion: {
    "1": {
      "AIMARA": 8578,
      "CHANGO": 9,
      "COLLA": 63,
      "DIAGUITA": 738,
      "KAWASHKAR": 1,
      "LICAN ANTAY o ATACAMEÑO": 105,
      "MAPUCHE": 923,
      "OTROS": 513,
      "QUECHUA": 534,
      "RAPA NUI": 4,
      "YAGAN o YÃMANA": 0
    },
    "2": {
      "AIMARA": 892,
      "CHANGO": 219,
      "COLLA": 51,
      "DIAGUITA": 1042,
      "KAWASHKAR": 0,
      "LICAN ANTAY o ATACAMEÑO": 6197,
      "MAPUCHE": 1306,
      "OTROS": 312,
      "QUECHUA": 1184,
      "RAPA NUI": 1,
      "YAGAN o YÃMANA": 0
    },
    "3": {
      "AIMARA": 163,
      "CHANGO": 418,
      "COLLA": 1840,
      "DIAGUITA": 4609,
      "KAWASHKAR": 0,
      "LICAN ANTAY o ATACAMEÑO": 30,
      "MAPUCHE": 833,
      "OTROS": 240,
      "QUECHUA": 12,
      "RAPA NUI": 1,
      "YAGAN o YÃMANA": 0
    },
    "4": {
      "AIMARA": 343,
      "CHANGO": 215,
      "COLLA": 81,
      "DIAGUITA": 2638,
      "KAWASHKAR": 0,
      "LICAN ANTAY o ATACAMEÑO": 116,
      "MAPUCHE": 1739,
      "OTROS": 139,
      "QUECHUA": 49,
      "RAPA NUI": 3,
      "YAGAN o YÃMANA": 3
    },
    "5": {
      "AIMARA": 434,
      "CHANGO": 12,
      "COLLA": 39,
      "DIAGUITA": 881,
      "KAWASHKAR": 12,
      "LICAN ANTAY o ATACAMEÑO": 75,
      "MAPUCHE": 7335,
      "OTROS": 344,
      "QUECHUA": 37,
      "RAPA NUI": 1772,
      "YAGAN o YÃMANA": 0
    },
    "6": {
      "AIMARA": 67,
      "CHANGO": 1,
      "COLLA": 4,
      "DIAGUITA": 68,
      "KAWASHKAR": 2,
      "LICAN ANTAY o ATACAMEÑO": 14,
      "MAPUCHE": 3708,
      "OTROS": 170,
      "QUECHUA": 5,
      "RAPA NUI": 3,
      "YAGAN o YÃMANA": 0
    },
    "7": {
      "AIMARA": 52,
      "CHANGO": 0,
      "COLLA": 0,
      "DIAGUITA": 51,
      "KAWASHKAR": 0,
      "LICAN ANTAY o ATACAMEÑO": 17,
      "MAPUCHE": 3435,
      "OTROS": 204,
      "QUECHUA": 6,
      "RAPA NUI": 1,
      "YAGAN o YÃMANA": 0
    },
    "8": {
      "AIMARA": 79,
      "CHANGO": 2,
      "COLLA": 1,
      "DIAGUITA": 37,
      "KAWASHKAR": 3,
      "LICAN ANTAY o ATACAMEÑO": 8,
      "MAPUCHE": 19251,
      "OTROS": 1845,
      "QUECHUA": 13,
      "RAPA NUI": 4,
      "YAGAN o YÃMANA": 4
    },
    "9": {
      "AIMARA": 25,
      "CHANGO": 0,
      "COLLA": 3,
      "DIAGUITA": 22,
      "KAWASHKAR": 1,
      "LICAN ANTAY o ATACAMEÑO": 6,
      "MAPUCHE": 56986,
      "OTROS": 8084,
      "QUECHUA": 0,
      "RAPA NUI": 6,
      "YAGAN o YÃMANA": 1
    },
    "10": {
      "AIMARA": 47,
      "CHANGO": 1,
      "COLLA": 3,
      "DIAGUITA": 21,
      "KAWASHKAR": 4,
      "LICAN ANTAY o ATACAMEÑO": 2,
      "MAPUCHE": 34102,
      "OTROS": 3569,
      "QUECHUA": 4,
      "RAPA NUI": 6,
      "YAGAN o YÃMANA": 1
    },
    "11": {
      "AIMARA": 12,
      "CHANGO": 0,
      "COLLA": 0,
      "DIAGUITA": 8,
      "KAWASHKAR": 0,
      "LICAN ANTAY o ATACAMEÑO": 1,
      "MAPUCHE": 3153,
      "OTROS": 301,
      "QUECHUA": 0,
      "RAPA NUI": 1,
      "YAGAN o YÃMANA": 0
    },
    "12": {
      "AIMARA": 14,
      "CHANGO": 0,
      "COLLA": 1,
      "DIAGUITA": 11,
      "KAWASHKAR": 216,
      "LICAN ANTAY o ATACAMEÑO": 3,
      "MAPUCHE": 3100,
      "OTROS": 310,
      "QUECHUA": 0,
      "RAPA NUI": 1,
      "YAGAN o YÃMANA": 43
    },
    "13": {
      "AIMARA": 827,
      "CHANGO": 17,
      "COLLA": 39,
      "DIAGUITA": 935,
      "KAWASHKAR": 5,
      "LICAN ANTAY o ATACAMEÑO": 138,
      "MAPUCHE": 66379,
      "OTROS": 1930,
      "QUECHUA": 55,
      "RAPA NUI": 63,
      "YAGAN o YÃMANA": 3
    },
    "14": {
      "AIMARA": 18,
      "CHANGO": 0,
      "COLLA": 0,
      "DIAGUITA": 10,
      "KAWASHKAR": 4,
      "LICAN ANTAY o ATACAMEÑO": 3,
      "MAPUCHE": 14470,
      "OTROS": 1187,
      "QUECHUA": 2,
      "RAPA NUI": 2,
      "YAGAN o YÃMANA": 0
    },
    "15": {
      "AIMARA": 7681,
      "CHANGO": 6,
      "COLLA": 11,
      "DIAGUITA": 151,
      "KAWASHKAR": 0,
      "LICAN ANTAY o ATACAMEÑO": 61,
      "MAPUCHE": 516,
      "OTROS": 411,
      "QUECHUA": 166,
      "RAPA NUI": 1,
      "YAGAN o YÃMANA": 0
    },
    "16": {
      "AIMARA": 23,
      "CHANGO": 0,
      "COLLA": 0,
      "DIAGUITA": 9,
      "KAWASHKAR": 0,
      "LICAN ANTAY o ATACAMEÑO": 4,
      "MAPUCHE": 1208,
      "OTROS": 59,
      "QUECHUA": 5,
      "RAPA NUI": 1,
      "YAGAN o YÃMANA": 0
    }
  }
};
