/**
 * Resultado Primarias Alcaldes Noviembre 2020
 * Datos agregados por región y partido desde votación por comuna
 */
export const alcaldesPrimarias202011 = {
    id: "alcaldes-primarias-2020-11",
    name: "Primarias Alcaldes Noviembre 2020",
    // Mapeo de cada partido a su pacto correspondiente
    pactoMapping: {
        "COMUNES": "FRENTE AMPLIO",
        "CONVERGENCIA SOCIAL": "FRENTE AMPLIO",
        "EVOLUCION POLITICA": "CHILE VAMOS",
        "INDEPENDIENTES": "ECOLOGISTAS E INDEPENDIENTES",
        "PARTIDO ECOLOGISTA VERDE": "ECOLOGISTAS E INDEPENDIENTES",
        "PARTIDO LIBERAL DE CHILE": "FRENTE AMPLIO",
        "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": "CHILE VAMOS",
        "RENOVACION NACIONAL": "CHILE VAMOS",
        "REVOLUCION DEMOCRATICA": "FRENTE AMPLIO",
        "UNION DEMOCRATA INDEPENDIENTE": "CHILE VAMOS",
        "VOTOS EN BLANCO": "VOTOS EN BLANCO",
        "VOTOS NULOS": "VOTOS NULOS"
    },
    // Votos desglosados por región
    votesByRegion: {
        "1": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 1093, "INDEPENDIENTES": 2772, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 1913, "VOTOS EN BLANCO": 699, "VOTOS NULOS": 882 },
        "2": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 1245, "INDEPENDIENTES": 0, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 1884, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 2017, "VOTOS EN BLANCO": 604, "VOTOS NULOS": 925 },
        "3": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 595, "INDEPENDIENTES": 3286, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 556, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 369, "VOTOS NULOS": 445 },
        "4": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "INDEPENDIENTES": 0, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 1310, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 1735, "VOTOS EN BLANCO": 225, "VOTOS NULOS": 335 },
        "5": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 4057, "EVOLUCION POLITICA": 4614, "INDEPENDIENTES": 4694, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 1278, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 3243, "REVOLUCION DEMOCRATICA": 6302, "UNION DEMOCRATA INDEPENDIENTE": 4536, "VOTOS EN BLANCO": 2426, "VOTOS NULOS": 3761 },
        "6": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 110, "INDEPENDIENTES": 0, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 2329, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 4438, "VOTOS EN BLANCO": 95, "VOTOS NULOS": 153 },
        "7": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 1201, "INDEPENDIENTES": 3877, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 855, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 862, "VOTOS EN BLANCO": 522, "VOTOS NULOS": 513 },
        "8": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 922, "INDEPENDIENTES": 1070, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 747, "RENOVACION NACIONAL": 343, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 268, "VOTOS EN BLANCO": 350, "VOTOS NULOS": 388 },
        "9": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 2581, "INDEPENDIENTES": 9955, "PARTIDO ECOLOGISTA VERDE": 1588, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 2109, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 355, "VOTOS NULOS": 491 },
        "11": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 947, "INDEPENDIENTES": 1552, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 1272, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 0, "VOTOS EN BLANCO": 342, "VOTOS NULOS": 416 },
        "13": { "COMUNES": 665, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 8548, "INDEPENDIENTES": 8338, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 628, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 273, "RENOVACION NACIONAL": 7413, "REVOLUCION DEMOCRATICA": 4611, "UNION DEMOCRATA INDEPENDIENTE": 14315, "VOTOS EN BLANCO": 890, "VOTOS NULOS": 1703 },
        "14": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 489, "INDEPENDIENTES": 0, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 173, "VOTOS EN BLANCO": 19, "VOTOS NULOS": 16 },
        "16": { "COMUNES": 0, "CONVERGENCIA SOCIAL": 0, "EVOLUCION POLITICA": 0, "INDEPENDIENTES": 699, "PARTIDO ECOLOGISTA VERDE": 0, "PARTIDO LIBERAL DE CHILE": 0, "PARTIDO REGIONALISTA INDEPENDIENTE DEMOCRATA": 0, "RENOVACION NACIONAL": 0, "REVOLUCION DEMOCRATICA": 0, "UNION DEMOCRATA INDEPENDIENTE": 257, "VOTOS EN BLANCO": 106, "VOTOS NULOS": 86 }
    }
};
